
CREATE TABLE tasks(
	ID INT NOT NULL AUTO_INCREMENT,
	userID INT NOT NULL,
	name VARCHAR(20),
	description VARCHAR(400),
	PRIMARY KEY(ID),
	FOREIGN KEY(userID) REFERENCES 
	users(ID) ON DELETE CASCADE
);